export interface Sticker {
  id: string;
  number: number;
  name: string;
  isFoil?: boolean;
  isTeamPhoto?: boolean;
  isShield?: boolean;
}

export interface Team {
  code: string;
  name: string;
  fullName: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor?: string;
  textOnPrimary?: string;
  stickers: Sticker[];
  order: number;
}

function makeStickers(teamCode: string, baseNumber: number, names: string[]): Sticker[] {
  return names.map((name, i) => {
    const number = baseNumber + i;
    const isFoil = name.endsWith('[FOIL]');
    const cleanName = name.replace(' [FOIL]', '');
    const isTeamPhoto = cleanName === 'Foto de Equipo';
    const isShield = cleanName.startsWith('Escudo');
    return {
      id: `${teamCode}${String(number).padStart(2, '0')}`,
      number,
      name: cleanName,
      isFoil,
      isTeamPhoto,
      isShield,
    };
  });
}

export const TEAMS: Team[] = [
  // ── INTRODUCCIÓN FWC ──────────────────────────────────────────
  {
    code: 'FWC',
    name: 'FWC',
    fullName: 'Introducción FWC',
    primaryColor: '#001440',
    secondaryColor: '#FFD700',
    accentColor: '#FFD700',
    textOnPrimary: '#FFD700',
    order: 0,
    stickers: makeStickers('FWC', 1, [
      'Panini Logo [FOIL]',
      'Emblema Oficial [FOIL]',
      'Emblema Oficial 2 [FOIL]',
      'Mascotas Oficiales [FOIL]',
      'Slogan Oficial [FOIL]',
      'Pelota Oficial [FOIL]',
      'Canadá Ciudades Sede [FOIL]',
      'México Ciudades Sede [FOIL]',
      'USA Ciudades Sede [FOIL]',
      'Italia 1934 [FOIL]',
      'Uruguay 1950 [FOIL]',
      'Alemania 1954 [FOIL]',
      'Brasil 1962 [FOIL]',
      'Alemania 1974 [FOIL]',
      'Argentina 1986 [FOIL]',
      'Brasil 1994 [FOIL]',
      'Brasil 2002 [FOIL]',
      'Italia 2006 [FOIL]',
      'Alemania 2014 [FOIL]',
      'Argentina 2022 [FOIL]',
    ]),
  },
  // ── SUDAMÉRICA ─────────────────────────────────────────────────
  {
    code: 'ARG',
    name: 'ARG',
    fullName: 'Argentina',
    primaryColor: '#74ACDF',
    secondaryColor: '#FFFFFF',
    accentColor: '#74ACDF',
    textOnPrimary: '#001440',
    order: 1,
    stickers: makeStickers('ARG', 1, [
      'Escudo AFA [FOIL]',
      'Emiliano Martínez',
      'Nahuel Molina',
      'Cristian Romero',
      'Nicolás Otamendi',
      'Nicolás Tagliafico',
      'Leonardo Balerdi',
      'Enzo Fernández',
      'Alexis Mac Allister',
      'Rodrigo De Paul',
      'Exequiel Palacios',
      'Leandro Paredes',
      'Foto de Equipo',
      'Nico Paz',
      'Franco Mastantuono',
      'Nicolás González',
      'Lionel Messi',
      'Lautaro Martínez',
      'Julián Álvarez',
      'Giuliano Simeone',
    ]),
  },
  {
    code: 'BRA',
    name: 'BRA',
    fullName: 'Brasil',
    primaryColor: '#009B3A',
    secondaryColor: '#FEDF00',
    accentColor: '#FEDF00',
    textOnPrimary: '#003087',
    order: 2,
    stickers: makeStickers('BRA', 1, [
      'Escudo CBF [FOIL]',
      'Alisson',
      'Bento',
      'Marquinhos',
      'Éder Militão',
      'Gabriel Magalhães',
      'Danilo',
      'Wesley',
      'Lucas Paquetá',
      'Casemiro',
      'Bruno Guimarães',
      'Luiz Henrique',
      'Foto de Equipo',
      'Vinicius Júnior',
      'Rodrygo',
      'João Pedro',
      'Matheus Cunha',
      'Gabriel Martinelli',
      'Raphinha',
      'Estêvão',
    ]),
  },
  {
    code: 'URU',
    name: 'URU',
    fullName: 'Uruguay',
    primaryColor: '#5EB6E4',
    secondaryColor: '#FFFFFF',
    accentColor: '#5EB6E4',
    textOnPrimary: '#001440',
    order: 3,
    stickers: makeStickers('URU', 1, [
      'Escudo AUF [FOIL]',
      'Sergio Rochet',
      'Santiago Mele',
      'Ronald Araújo',
      'José María Giménez',
      'Sebastián Cáceres',
      'Mathias Olivera',
      'Guillermo Varela',
      'Nahitan Nández',
      'Federico Valverde',
      'Giorgian De Arrascaeta',
      'Rodrigo Bentancur',
      'Foto de Equipo',
      'Manuel Ugarte',
      'Nicolás de la Cruz',
      'Maximiliano Araújo',
      'Darwin Núñez',
      'Federico Viñas',
      'Rodrigo Aguirre',
      'Facundo Pellistri',
    ]),
  },
  {
    code: 'COL',
    name: 'COL',
    fullName: 'Colombia',
    primaryColor: '#FCD116',
    secondaryColor: '#003087',
    accentColor: '#CE1126',
    textOnPrimary: '#001440',
    order: 4,
    stickers: makeStickers('COL', 1, [
      'Escudo FCF [FOIL]',
      'Camilo Vargas',
      'Daniel Muñoz',
      'Dávinson Sánchez',
      'Carlos Cuesta',
      'Johan Mojica',
      'Jhon Lucumí',
      'Gustavo Puerta',
      'Santiago Arias',
      'Jefferson Lerma',
      'Richard Ríos',
      'Juan Fernando Quintero',
      'Foto de Equipo',
      'James Rodríguez',
      'Jhon Jáder Durán',
      'Luis Díaz',
      'Jhon Córdoba',
      'Rafael Santos Borré',
      'Cucho Hernández',
      'Déiver Machado',
    ]),
  },
  {
    code: 'ECU',
    name: 'ECU',
    fullName: 'Ecuador',
    primaryColor: '#FFD100',
    secondaryColor: '#003580',
    accentColor: '#CE1126',
    textOnPrimary: '#001440',
    order: 5,
    stickers: makeStickers('ECU', 1, [
      'Escudo FEF [FOIL]',
      'Hernán Galíndez',
      'Gonzalo Valle',
      'Piero Hincapié',
      'Pervis Estupiñán',
      'Willian Pacho',
      'Ángelo Preciado',
      'Joel Ordóñez',
      'Moisés Caicedo',
      'Alan Franco',
      'Kendry Páez',
      'Pedro Vite',
      'Foto de Equipo',
      'John Yeboah',
      'Leonardo Campana',
      'Gonzalo Plata',
      'Nilson Angulo',
      'Alan Minda',
      'Kevin Rodríguez',
      'Enner Valencia',
    ]),
  },
  {
    code: 'PAR',
    name: 'PAR',
    fullName: 'Paraguay',
    primaryColor: '#D52B1E',
    secondaryColor: '#002868',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 6,
    stickers: makeStickers('PAR', 1, [
      'Escudo APF [FOIL]',
      'Roberto Fernández',
      'Orlando Gill',
      'Gustavo Gómez',
      'Fabián Balbuena',
      'Juan José Cáceres',
      'Omar Alderete',
      'Junior Alonso',
      'Mathías Villasanti',
      'Diego Gómez',
      'Damián Bobadilla',
      'Andrés Cubas',
      'Foto de Equipo',
      'Matías Galarza',
      'Julio Enciso',
      'Alejandro Romero Gamarra',
      'Miguel Almirón',
      'Ramón Sosa',
      'Ángel Romero',
      'Antonio Sanabria',
    ]),
  },
  // ── EUROPA ────────────────────────────────────────────────────
  {
    code: 'ESP',
    name: 'ESP',
    fullName: 'España',
    primaryColor: '#AA151B',
    secondaryColor: '#F1BF00',
    accentColor: '#F1BF00',
    textOnPrimary: '#FFFFFF',
    order: 7,
    stickers: makeStickers('ESP', 1, [
      'Escudo RFEF [FOIL]',
      'Unai Simón',
      'Robin Le Normand',
      'Aymeric Laporte',
      'Dean Huijsen',
      'Pedro Porro',
      'Dani Carvajal',
      'Marc Cucurella',
      'Martín Zubimendi',
      'Rodri',
      'Pedri',
      'Fabián Ruiz',
      'Foto de Equipo',
      'Mikel Merino',
      'Lamine Yamal',
      'Dani Olmo',
      'Nico Williams',
      'Ferran Torres',
      'Álvaro Morata',
      'Mikel Oyarzabal',
    ]),
  },
  {
    code: 'FRA',
    name: 'FRA',
    fullName: 'Francia',
    primaryColor: '#002395',
    secondaryColor: '#ED2939',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 8,
    stickers: makeStickers('FRA', 1, [
      'Escudo FFF [FOIL]',
      'Mike Maignan',
      'Theo Hernández',
      'William Saliba',
      'Jules Koundé',
      'Ibrahima Konaté',
      'Dayot Upamecano',
      'Lucas Digne',
      'Aurélien Tchouaméni',
      'Eduardo Camavinga',
      'Manu Koné',
      'Adrien Rabiot',
      'Foto de Equipo',
      'Michael Olise',
      'Ousmane Dembélé',
      'Bradley Barcola',
      'Désiré Doué',
      'Kingsley Coman',
      'Hugo Ekitike',
      'Kylian Mbappé',
    ]),
  },
  {
    code: 'GER',
    name: 'GER',
    fullName: 'Alemania',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    textOnPrimary: '#FFFFFF',
    order: 9,
    stickers: makeStickers('GER', 1, [
      'Escudo DFB [FOIL]',
      'Marc-André ter Stegen',
      'Jonathan Tah',
      'David Raum',
      'Nico Schlotterbeck',
      'Antonio Rüdiger',
      'Waldemar Anton',
      'Ridle Baku',
      'Maximilian Mittelstädt',
      'Joshua Kimmich',
      'Florian Wirtz',
      'Felix Nmecha',
      'Foto de Equipo',
      'Leon Goretzka',
      'Jamal Musiala',
      'Serge Gnabry',
      'Kai Havertz',
      'Leroy Sané',
      'Karim Adeyemi',
      'Nick Woltemade',
    ]),
  },
  {
    code: 'POR',
    name: 'POR',
    fullName: 'Portugal',
    primaryColor: '#006600',
    secondaryColor: '#CC0000',
    accentColor: '#FFD700',
    textOnPrimary: '#FFFFFF',
    order: 10,
    stickers: makeStickers('POR', 1, [
      'Escudo FPF [FOIL]',
      'Diogo Costa',
      'José Sá',
      'Rúben Dias',
      'João Cancelo',
      'Diogo Dalot',
      'Nuno Mendes',
      'Pepe',
      'Bernardo Silva',
      'João Palhinha',
      'Vitinha',
      'Bruno Fernandes',
      'Foto de Equipo',
      'Rafael Leão',
      'João Félix',
      'Pedro Neto',
      'Francisco Conceição',
      'Rafa Silva',
      'Gonçalo Ramos',
      'Cristiano Ronaldo',
    ]),
  },
  {
    code: 'NED',
    name: 'NED',
    fullName: 'Países Bajos',
    primaryColor: '#FF6600',
    secondaryColor: '#FFFFFF',
    accentColor: '#003082',
    textOnPrimary: '#FFFFFF',
    order: 11,
    stickers: makeStickers('NED', 1, [
      'Escudo KNVB [FOIL]',
      'Bart Verbruggen',
      'Virgil van Dijk',
      'Micky van de Ven',
      'Jurriën Timber',
      'Denzel Dumfries',
      'Nathan Aké',
      'Jeremie Frimpong',
      'Jan Paul van Hecke',
      'Tijjani Reijnders',
      'Ryan Gravenberch',
      'Teun Koopmeiners',
      'Foto de Equipo',
      'Frenkie de Jong',
      'Xavi Simons',
      'Justin Kluivert',
      'Memphis Depay',
      'Donyell Malen',
      'Wout Weghorst',
      'Cody Gakpo',
    ]),
  },
  {
    code: 'BEL',
    name: 'BEL',
    fullName: 'Bélgica',
    primaryColor: '#EF3340',
    secondaryColor: '#000000',
    accentColor: '#FDDA24',
    textOnPrimary: '#FFFFFF',
    order: 12,
    stickers: makeStickers('BEL', 1, [
      'Escudo RBFA [FOIL]',
      'Thibaut Courtois',
      'Arthur Theate',
      'Timothy Castagne',
      'Zeno Debast',
      'Brandon Mechele',
      'Maxim De Cuyper',
      'Thomas Meunier',
      'Youri Tielemans',
      'Amadou Onana',
      'Nicolas Raskin',
      'Alexis Saelemaekers',
      'Foto de Equipo',
      'Hans Vanaken',
      'Kevin De Bruyne',
      'Jérémy Doku',
      'Charles De Ketelaere',
      'Leandro Trossard',
      'Loïs Openda',
      'Romelu Lukaku',
    ]),
  },
  {
    code: 'SUI',
    name: 'SUI',
    fullName: 'Suiza',
    primaryColor: '#D52B1E',
    secondaryColor: '#FFFFFF',
    accentColor: '#D52B1E',
    textOnPrimary: '#FFFFFF',
    order: 13,
    stickers: makeStickers('SUI', 1, [
      'Escudo SFV [FOIL]',
      'Gregor Kobel',
      'Yvon Mvogo',
      'Manuel Akanji',
      'Ricardo Rodríguez',
      'Nico Elvedi',
      'Aurèle Amenda',
      'Silvan Widmer',
      'Granit Xhaka',
      'Denis Zakaria',
      'Remo Freuler',
      'Fabian Rieder',
      'Foto de Equipo',
      'Ardon Jashari',
      'Johan Manzambi',
      'Michel Aebischer',
      'Breel Embolo',
      'Ruben Vargas',
      'Dan Ndoye',
      'Zeki Amdouni',
    ]),
  },
  {
    code: 'AUT',
    name: 'AUT',
    fullName: 'Austria',
    primaryColor: '#ED2939',
    secondaryColor: '#FFFFFF',
    accentColor: '#ED2939',
    textOnPrimary: '#FFFFFF',
    order: 14,
    stickers: makeStickers('AUT', 1, [
      'Escudo ÖFB [FOIL]',
      'Alexander Schlager',
      'Patrick Pentz',
      'David Alaba',
      'Kevin Danso',
      'Philipp Lienhart',
      'Stefan Posch',
      'Phillipp Mwene',
      'Alexander Prass',
      'Xaver Schlager',
      'Marcel Sabitzer',
      'Konrad Laimer',
      'Foto de Equipo',
      'Florian Grillitsch',
      'Nicolas Seiwald',
      'Romano Schmid',
      'Patrick Wimmer',
      'Christoph Baumgartner',
      'Michael Gregoritsch',
      'Marko Arnautović',
    ]),
  },
  {
    code: 'SCO',
    name: 'SCO',
    fullName: 'Escocia',
    primaryColor: '#003082',
    secondaryColor: '#FFFFFF',
    accentColor: '#003082',
    textOnPrimary: '#FFFFFF',
    order: 15,
    stickers: makeStickers('SCO', 1, [
      'Escudo SFA [FOIL]',
      'Angus Gunn',
      'Jack Hendry',
      'Kieran Tierney',
      'Aaron Hickey',
      'Andrew Robertson',
      'Scott McKenna',
      'John Souttar',
      'Anthony Ralston',
      'Grant Hanley',
      'Scott McTominay',
      'Billy Gilmour',
      'Foto de Equipo',
      'Lewis Ferguson',
      'Ryan Christie',
      'Kenny McLean',
      'John McGinn',
      'Lyndon Dykes',
      'Che Adams',
      'Ben Doak',
    ]),
  },
  {
    code: 'NOR',
    name: 'NOR',
    fullName: 'Noruega',
    primaryColor: '#EF2B2D',
    secondaryColor: '#FFFFFF',
    accentColor: '#002868',
    textOnPrimary: '#FFFFFF',
    order: 16,
    stickers: makeStickers('NOR', 1, [
      'Escudo NFF [FOIL]',
      'Ørjan Nyland',
      'Julian Ryerson',
      'Leo Ostigård',
      'Kristoffer Ajer',
      'Marcus Holmgren Pedersen',
      'David Møller Wolfe',
      'Torbjørn Heggem',
      'Morten Thorsby',
      'Martin Ødegaard',
      'Sander Berge',
      'Andreas Schjelderup',
      'Foto de Equipo',
      'Patrick Berg',
      'Erling Haaland',
      'Alexander Sørloth',
      'Aron Dønnum',
      'Jørgen Strand Larsen',
      'Antonio Nusa',
      'Oscar Bobb',
    ]),
  },
  {
    code: 'SWE',
    name: 'SWE',
    fullName: 'Suecia',
    primaryColor: '#006AA7',
    secondaryColor: '#FECC02',
    accentColor: '#FECC02',
    textOnPrimary: '#FFFFFF',
    order: 17,
    stickers: makeStickers('SWE', 1, [
      'Escudo SvFF [FOIL]',
      'Victor Johansson',
      'Isak Hien',
      'Gabriel Gudmundsson',
      'Emil Holm',
      'Victor Nilsson Lindelöf',
      'Gustaf Lagerbielke',
      'Lucas Bergvall',
      'Hugo Larsson',
      'Jesper Karlström',
      'Yasin Ayari',
      'Mattias Svanberg',
      'Foto de Equipo',
      'Daniel Svensson',
      'Ken Sema',
      'Roony Bardghji',
      'Dejan Kulusevski',
      'Anthony Elanga',
      'Alexander Isak',
      'Viktor Gyökeres',
    ]),
  },
  {
    code: 'TUR',
    name: 'TUR',
    fullName: 'Türkiye',
    primaryColor: '#E30A17',
    secondaryColor: '#FFFFFF',
    accentColor: '#E30A17',
    textOnPrimary: '#FFFFFF',
    order: 18,
    stickers: makeStickers('TUR', 1, [
      'Escudo TFF [FOIL]',
      'Ugurcan Çakir',
      'Mert Müldür',
      'Zeki Çelik',
      'Abdülkerim Bardakci',
      'Çaglar Söyüncü',
      'Merih Demiral',
      'Ferdi Kadioglu',
      'Kaan Ayhan',
      'Ismail Yüksek',
      'Hakan Çalhanoğlu',
      'Orkun Kökçü',
      'Foto de Equipo',
      'Arda Güler',
      'Irfan Can Kahveci',
      'Yunus Akgün',
      'Can Uzun',
      'Barış Alper Yilmaz',
      'Kerem Aktürkoğlu',
      'Kenan Yildiz',
    ]),
  },
  {
    code: 'CRO',
    name: 'CRO',
    fullName: 'Croacia',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#003082',
    textOnPrimary: '#FFFFFF',
    order: 19,
    stickers: makeStickers('CRO', 1, [
      'Escudo HNS [FOIL]',
      'Dominik Livaković',
      'Josip Stanišić',
      'Joško Gvardiol',
      'Martin Erlić',
      'Marin Pongračić',
      'Borna Sosa',
      'Luka Vušković',
      'Mario Pašalić',
      'Mateo Kovačić',
      'Kristijan Jakić',
      'Lovro Majer',
      'Foto de Equipo',
      'Luka Modrić',
      'Ivan Perišić',
      'Marcelo Brozović',
      'Andrej Kramarić',
      'Bruno Petković',
      'Marko Livaja',
      'Mislav Oršić',
    ]),
  },
  {
    code: 'CZE',
    name: 'CZE',
    fullName: 'Rep. Checa',
    primaryColor: '#D7141A',
    secondaryColor: '#FFFFFF',
    accentColor: '#11457E',
    textOnPrimary: '#FFFFFF',
    order: 20,
    stickers: makeStickers('CZE', 1, [
      'Escudo FAČR [FOIL]',
      'Matej Kovář',
      'Jindřich Staněk',
      'Ladislav Krejčí',
      'Vladimír Coufal',
      'Jaroslav Zelený',
      'Tomáš Holeš',
      'David Zima',
      'Michal Sadílek',
      'Lukáš Provod',
      'Lukáš Červ',
      'Tomáš Souček',
      'Foto de Equipo',
      'Pavel Šulc',
      'Matěj Vydra',
      'Vasil Kušej',
      'Tomáš Chorý',
      'Václav Černý',
      'Adam Hložek',
      'Patrik Schick',
    ]),
  },
  {
    code: 'BIH',
    name: 'BIH',
    fullName: 'Bosnia-Herz.',
    primaryColor: '#003DA5',
    secondaryColor: '#FBCE07',
    accentColor: '#003DA5',
    textOnPrimary: '#FFFFFF',
    order: 21,
    stickers: makeStickers('BIH', 1, [
      'Escudo NFSBiH [FOIL]',
      'Nikola Vasilj',
      'Amer Dedić',
      'Sead Kolašinac',
      'Tarik Muharemović',
      'Nihad Mujakić',
      'Nikola Katić',
      'Amir Hadžiahmetović',
      'Benjamin Tahirović',
      'Armin Gigović',
      'Ivan Šunjić',
      'Ivan Bašić',
      'Foto de Equipo',
      'Dženis Burnić',
      'Esmir Bajraktarević',
      'Amar Memić',
      'Ermedin Demirović',
      'Edin Džeko',
      'Samed Baždar',
      'Haris Tabakovic',
    ]),
  },
  {
    code: 'ENG',
    name: 'ENG',
    fullName: 'Inglaterra',
    primaryColor: '#012169',
    secondaryColor: '#FFFFFF',
    accentColor: '#CF142B',
    textOnPrimary: '#FFFFFF',
    order: 22,
    stickers: makeStickers('ENG', 1, [
      'Escudo FA [FOIL]',
      'Jordan Pickford',
      'Morgan Rogers',
      'John Stones',
      'Harry Maguire',
      'Ben White',
      'Trent Alexander-Arnold',
      'Luke Shaw',
      'Declan Rice',
      'Jude Bellingham',
      'Phil Foden',
      'Bukayo Saka',
      'Foto de Equipo',
      'Jordan Henderson',
      'Reece James',
      'Cole Palmer',
      'Harry Kane',
      'Ollie Watkins',
      'Ivan Toney',
      'Marcus Rashford',
    ]),
  },
  // ── ÁFRICA ────────────────────────────────────────────────────
  {
    code: 'MAR',
    name: 'MAR',
    fullName: 'Marruecos',
    primaryColor: '#C1272D',
    secondaryColor: '#006233',
    accentColor: '#C1272D',
    textOnPrimary: '#FFFFFF',
    order: 23,
    stickers: makeStickers('MAR', 1, [
      'Escudo FRMF [FOIL]',
      'Yassine Bounou',
      'Munir El Kajoui',
      'Achraf Hakimi',
      'Noussair Mazraoui',
      'Nayef Aguerd',
      'Romain Saïss',
      'Jawad El Yamiq',
      'Adam Masina',
      'Sofyan Amrabat',
      'Azzedine Ounahi',
      'Eliesse Ben Seghir',
      'Foto de Equipo',
      'Bilal El Khannouss',
      'Ismael Saibari',
      'Youssef En-Nesyri',
      'Abde Ezzalzouli',
      'Soufiane Rahimi',
      'Brahim Díaz',
      'Ayoub El Kaabi',
    ]),
  },
  {
    code: 'SEN',
    name: 'SEN',
    fullName: 'Senegal',
    primaryColor: '#00853F',
    secondaryColor: '#FDEF42',
    accentColor: '#E31B23',
    textOnPrimary: '#FFFFFF',
    order: 24,
    stickers: makeStickers('SEN', 1, [
      'Escudo FSF [FOIL]',
      'Édouard Mendy',
      'Yehvann Diouf',
      'Moussa Niakhaté',
      'Abdoulaye Seck',
      'Ismail Jakobs',
      'El Hadji Malick Diouf',
      'Kalidou Koulibaly',
      'Idrissa Gana Gueye',
      'Pape Matar Sarr',
      'Pape Gueye',
      'Habib Diarra',
      'Foto de Equipo',
      'Lamine Camara',
      'Sadio Mané',
      'Ismaïla Sarr',
      'Boulaye Dia',
      'Iliman Ndiaye',
      'Nicolas Jackson',
      'Krepin Diatta',
    ]),
  },
  {
    code: 'EGY',
    name: 'EGY',
    fullName: 'Egipto',
    primaryColor: '#C8102E',
    secondaryColor: '#FFFFFF',
    accentColor: '#000000',
    textOnPrimary: '#FFFFFF',
    order: 25,
    stickers: makeStickers('EGY', 1, [
      'Escudo EFA [FOIL]',
      'Mohamed El Shenawy',
      'Mohamed Hany',
      'Mohamed Hamdy',
      'Yasser Ibrahim',
      'Khaled Sobhi',
      'Ramy Rabia',
      'Hossam Abdelmaguid',
      'Ahmed Fatouh',
      'Marwan Attia',
      'Zizo',
      'Hamdy Fathy',
      'Foto de Equipo',
      'Mohamed Lasheen',
      'Emam Ashour',
      'Osama Faisal',
      'Mohamed Salah',
      'Mostafa Mohamed',
      'Trezeguet',
      'Omar Marmoush',
    ]),
  },
  {
    code: 'ALG',
    name: 'ALG',
    fullName: 'Argelia',
    primaryColor: '#006233',
    secondaryColor: '#FFFFFF',
    accentColor: '#D21034',
    textOnPrimary: '#FFFFFF',
    order: 26,
    stickers: makeStickers('ALG', 1, [
      'Escudo FAF [FOIL]',
      'Alexis Guendouz',
      'Ramy Bensebaini',
      'Youcef Atal',
      'Rayan Aït-Nouri',
      'Mohamed Amine Tougai',
      'Aïssa Mandi',
      'Ismael Bennacer',
      'Houssem Aouar',
      'Hicham Boudaoui',
      'Ramiz Zerrouki',
      'Nabil Bentalab',
      'Foto de Equipo',
      'Farès Chaibi',
      'Riyad Mahrez',
      'Saïd Benrahma',
      'Anis Hadj Moussa',
      'Amine Gouiri',
      'Baghdad Bounedjah',
      'Mohammed Amoura',
    ]),
  },
  {
    code: 'RSA',
    name: 'RSA',
    fullName: 'Sudáfrica',
    primaryColor: '#007A4D',
    secondaryColor: '#FFB612',
    accentColor: '#001489',
    textOnPrimary: '#FFFFFF',
    order: 27,
    stickers: makeStickers('RSA', 1, [
      'Escudo SAFA [FOIL]',
      'Ronwen Williams',
      'Sipho Chaine',
      'Aubrey Modiba',
      'Samukele Kabini',
      'Mbekezeli Mbokazi',
      'Khulumani Ndamane',
      'Siyabonga Ngezana',
      'Khuliso Mudau',
      'Nkosinathi Sibisi',
      'Teboho Mokoena',
      'Thalente Mbatha',
      'Foto de Equipo',
      'Bathasi Aubaas',
      'Yaya Sithole',
      'Sipho Mbule',
      'Lyle Foster',
      'Iqraam Rayners',
      'Mohau Nkota',
      'Oswin Appollis',
    ]),
  },
  {
    code: 'TUN',
    name: 'TUN',
    fullName: 'Túnez',
    primaryColor: '#E70013',
    secondaryColor: '#FFFFFF',
    accentColor: '#E70013',
    textOnPrimary: '#FFFFFF',
    order: 28,
    stickers: makeStickers('TUN', 1, [
      'Escudo FTF [FOIL]',
      'Bechir Ben Said',
      'Aymen Dahmen',
      'Yan Valery',
      'Montassar Talbi',
      'Yassine Meriah',
      'Ali Abdi',
      'Dylan Bronn',
      'Ellyes Skhiri',
      'Aïssa Laidouni',
      'Ferjani Sassi',
      'Mohamed Ali Ben Romdhane',
      'Foto de Equipo',
      'Hannibal Mejbri',
      'Elias Achouri',
      'Elias Saad',
      'Hazem Mastouri',
      'Ismael Gharbi',
      'Sayfallah Ltaief',
      'Naim Sliti',
    ]),
  },
  {
    code: 'CPV',
    name: 'CPV',
    fullName: 'Cabo Verde',
    primaryColor: '#003893',
    secondaryColor: '#CF2027',
    accentColor: '#F7D116',
    textOnPrimary: '#FFFFFF',
    order: 29,
    stickers: makeStickers('CPV', 1, [
      'Escudo FCF [FOIL]',
      'Vozinha',
      'Logan Costa',
      'Pico',
      'Diney',
      'Steven Moreira',
      'Wagner Pina',
      'João Paulo',
      'Yannick Semedo',
      'Kevin Pina',
      'Patrick Andrade',
      'Jamiro Monteiro',
      'Foto de Equipo',
      'Deroy Duarte',
      'Garry Rodrigues',
      'Jovane Cabral',
      'Ryan Mendes',
      'Dailon Livramento',
      'Willy Semedo',
      'Bebé',
    ]),
  },
  {
    code: 'CIV',
    name: 'CIV',
    fullName: 'Costa de Marfil',
    primaryColor: '#F77F00',
    secondaryColor: '#009A44',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 30,
    stickers: makeStickers('CIV', 1, [
      'Escudo FIF [FOIL]',
      'Yahia Fofana',
      'Ghislain Konan',
      'Wilfried Singo',
      'Odilon Kossounou',
      'Evan N\'Dicka',
      'Willy Boly',
      'Emmanuel Agbadou',
      'Ousmane Diomandé',
      'Franck Kessié',
      'Seko Fofana',
      'Ibrahim Sangaré',
      'Foto de Equipo',
      'Jean-Philippe Gbamin',
      'Amad Diallo',
      'Sébastien Haller',
      'Simon Adingra',
      'Yan Diomandé',
      'Evann Guessand',
      'Oumar Diakité',
    ]),
  },
  {
    code: 'COD',
    name: 'COD',
    fullName: 'Congo DR',
    primaryColor: '#007FFF',
    secondaryColor: '#CE1021',
    accentColor: '#F7D618',
    textOnPrimary: '#FFFFFF',
    order: 31,
    stickers: makeStickers('COD', 1, [
      'Escudo FECOFA [FOIL]',
      'Lionel Mpasi',
      'Chancel Mbemba',
      'Arthur Masuaku',
      'Dylan Batubinsika',
      'Issa Kaboré',
      'Edo Kayembe',
      'Cédric Bakambu',
      'Yoane Wissa',
      'Samuel Moutoussamy',
      'Théo Bongonda',
      'Silas Katompa',
      'Foto de Equipo',
      'Boli Bolingoli',
      'Dodi Lukébakio',
      'Fiston Mayele',
      'Chadrac Akolo',
      'Jonathan Bolingi',
      'Gaël Kakuta',
      'Paul-José M\'Poku',
    ]),
  },
  // ── ASIA ──────────────────────────────────────────────────────
  {
    code: 'JPN',
    name: 'JPN',
    fullName: 'Japón',
    primaryColor: '#003087',
    secondaryColor: '#FFFFFF',
    accentColor: '#BC002D',
    textOnPrimary: '#FFFFFF',
    order: 32,
    stickers: makeStickers('JPN', 1, [
      'Escudo JFA [FOIL]',
      'Zion Suzuki',
      'Henry Heroki Mochizuki',
      'Ayumu Seko',
      'Junnosuke Suzuki',
      'Shogo Taniguchi',
      'Tsuyoshi Watanabe',
      'Kaishu Sano',
      'Yuki Soma',
      'Ao Tanaka',
      'Daichi Kamada',
      'Takefusa Kubo',
      'Foto de Equipo',
      'Ritsu Doan',
      'Keito Nakamura',
      'Takumi Minamino',
      'Shuto Machino',
      'Junya Ito',
      'Koki Ogawa',
      'Ayase Ueda',
    ]),
  },
  {
    code: 'KOR',
    name: 'KOR',
    fullName: 'Corea del Sur',
    primaryColor: '#CD2E3A',
    secondaryColor: '#0047A0',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 33,
    stickers: makeStickers('KOR', 1, [
      'Escudo KFA [FOIL]',
      'Hyeon-woo Jo',
      'Seung-Gyu Kim',
      'Min-jae Kim',
      'Yu-min Cho',
      'Young-woo Seol',
      'Han-beom Lee',
      'Tae-seok Lee',
      'Myung-jae Lee',
      'Jae-sung Lee',
      'In-beom Hwang',
      'Kang-in Lee',
      'Foto de Equipo',
      'Seung-ho Paik',
      'Jens Castrop',
      'Dongg-yeong Lee',
      'Gue-sung Cho',
      'Heung-min Son',
      'Hee-chan Hwang',
      'Hyeon-Gyu Oh',
    ]),
  },
  {
    code: 'KSA',
    name: 'KSA',
    fullName: 'Arabia Saudita',
    primaryColor: '#006C35',
    secondaryColor: '#FFFFFF',
    accentColor: '#006C35',
    textOnPrimary: '#FFFFFF',
    order: 34,
    stickers: makeStickers('KSA', 1, [
      'Escudo SAFF [FOIL]',
      'Nawaf Alaqidi',
      'Abdulrahman Al-Sanbi',
      'Saud Abdulhamid',
      'Nawaf Bouwashl',
      'Jihad Thakri',
      'Moteb Al-Harbi',
      'Hassan Altambakti',
      'Musab Aljuwayr',
      'Ziyad Aljohani',
      'Abdullah Alkhaibari',
      'Nasser Aldawsari',
      'Foto de Equipo',
      'Saleh Abu Alshamat',
      'Marwan Alsahafi',
      'Salem Aldawsari',
      'Abdulrahman Al-Aboud',
      'Feras Akbrikan',
      'Saleh Alshehri',
      'Abdullah Al-Hamdan',
    ]),
  },
  {
    code: 'IRN',
    name: 'IRN',
    fullName: 'Irán',
    primaryColor: '#239F40',
    secondaryColor: '#FFFFFF',
    accentColor: '#DA0000',
    textOnPrimary: '#FFFFFF',
    order: 35,
    stickers: makeStickers('IRN', 1, [
      'Escudo FFIRI [FOIL]',
      'Alireza Beiranvand',
      'Morteza Pouraliganji',
      'Ehsan Hajsafi',
      'Milad Mohammadi',
      'Shojae Khalilzadeh',
      'Ramin Rezaeian',
      'Hossein Kanaani',
      'Sadegh Moharrami',
      'Saleh Hardani',
      'Saeed Ezatolahi',
      'Saman Ghoddos',
      'Foto de Equipo',
      'Omid Noorafkan',
      'Roozbeh Cheshmi',
      'Mohammad Mohebi',
      'Sardar Azmoun',
      'Mehdi Taremi',
      'Alireza Jahanbakhsh',
      'Ali Gholizadeh',
    ]),
  },
  {
    code: 'IRQ',
    name: 'IRQ',
    fullName: 'Irak',
    primaryColor: '#007A3D',
    secondaryColor: '#CE1126',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 36,
    stickers: makeStickers('IRQ', 1, [
      'Escudo IFA [FOIL]',
      'Jalal Hassan',
      'Rebin Sulaka',
      'Hussein Ali',
      'Akam Hashem',
      'Merchas Doski',
      'Zaid Tahseen',
      'Manaf Younis',
      'Zidane Iqbal',
      'Amir Al-Ammari',
      'Ibrahim Bavesh',
      'Ali Jasim',
      'Foto de Equipo',
      'Youssef Amyn',
      'Aimar Sher',
      'Marko Farji',
      'Osama Rashid',
      'Ali Al-Hamadi',
      'Aymen Hussein',
      'Mohanad Ali',
    ]),
  },
  {
    code: 'JOR',
    name: 'JOR',
    fullName: 'Jordania',
    primaryColor: '#007A3D',
    secondaryColor: '#CE1126',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 37,
    stickers: makeStickers('JOR', 1, [
      'Escudo JFA [FOIL]',
      'Yazeed Abulaila',
      'Ihsan Haddad',
      'Mohammad Abu Hashish',
      'Yazan Al-Arab',
      'Abdallah Nasib',
      'Saleem Obaid',
      'Mohammad Abualnadi',
      'Ibrahim Saadeh',
      'Nizar Al-Rashdan',
      'Noor Al-Rawabdeh',
      'Mohannad Abu Taha',
      'Foto de Equipo',
      'Amer Jamous',
      'Musa Al-Taamari',
      'Yazan Al-Naimat',
      'Mahmoud Al-Mardi',
      'Ali Olwan',
      'Mohammad Abu Zrayq',
      'Ibrahim Sabra',
    ]),
  },
  {
    code: 'UZB',
    name: 'UZB',
    fullName: 'Uzbekistán',
    primaryColor: '#1EB53A',
    secondaryColor: '#0099B5',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 38,
    stickers: makeStickers('UZB', 1, [
      'Escudo UFA [FOIL]',
      'Utkir Yusupov',
      'Farrukh Savfiev',
      'Sherzod Nasrullaev',
      'Umar Eshmurodov',
      'Husniddin Aliqulov',
      'Rustamjon Ashurmatov',
      'Khojiakbar Alijonov',
      'Abdukodir Khusanov',
      'Odiljon Hamrobekov',
      'Otabek Shukurov',
      'Jamshid Iskanderov',
      'Foto de Equipo',
      'Eldor Shomurodov',
      'Shamsiddin Karimov',
      'Jasurbek Yakhshiboev',
      'Umid Hmalov',
      'Khojimat Erkinov',
      'Nodirbek Abdullayev',
      'Zuriko Davitashvili',
    ]),
  },
  {
    code: 'QAT',
    name: 'QAT',
    fullName: 'Qatar',
    primaryColor: '#8D1B3D',
    secondaryColor: '#FFFFFF',
    accentColor: '#8D1B3D',
    textOnPrimary: '#FFFFFF',
    order: 39,
    stickers: makeStickers('QAT', 1, [
      'Escudo QFA [FOIL]',
      'Meshaal Barsham',
      'Sultan Albrake',
      'Lucas Mendes',
      'Homam Ahmed',
      'Boualem Khoukhi',
      'Pedro Miguel',
      'Tarek Salman',
      'Mohamed Al-Mannai',
      'Karim Boudiaf',
      'Assim Madibo',
      'Ahmed Fatehi',
      'Foto de Equipo',
      'Mohammed Waad',
      'Abdulaziz Hatem',
      'Hassan Al-Haydos',
      'Edmilson Junior',
      'Akram Hassan Afif',
      'Ahmed Al Ganehi',
      'Almoez Ali',
    ]),
  },
  // ── OCEANÍA ───────────────────────────────────────────────────
  {
    code: 'AUS',
    name: 'AUS',
    fullName: 'Australia',
    primaryColor: '#00843D',
    secondaryColor: '#FFD700',
    accentColor: '#002868',
    textOnPrimary: '#FFFFFF',
    order: 40,
    stickers: makeStickers('AUS', 1, [
      'Escudo FFsA [FOIL]',
      'Mathew Ryan',
      'Joe Gauci',
      'Harry Souttar',
      'Alessandro Circati',
      'Jordan Bos',
      'Aziz Behich',
      'Cameron Burgess',
      'Lewis Miller',
      'Milos Degenek',
      'Jackson Irvine',
      'Riley McGree',
      'Foto de Equipo',
      'Aiden O\'Neill',
      'Connor Metcalfe',
      'Patrick Yazbek',
      'Craig Goodwin',
      'Kusini Vengi',
      'Nestory Irankunda',
      'Mohamed Touré',
    ]),
  },
  {
    code: 'NZL',
    name: 'NZL',
    fullName: 'Nueva Zelanda',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    accentColor: '#C8102E',
    textOnPrimary: '#FFFFFF',
    order: 41,
    stickers: makeStickers('NZL', 1, [
      'Escudo NZF [FOIL]',
      'Max Crocombe',
      'Alex Paulsen',
      'Michael Boxall',
      'Liberato Cacace',
      'Tim Payne',
      'Tyler Bindon',
      'Francis de Vries',
      'Finn Surman',
      'Joe Bell',
      'Sarpreet Singh',
      'Ryan Thomas',
      'Foto de Equipo',
      'Matthew Garbett',
      'Marko Stamenić',
      'Ben Old',
      'Chris Wood',
      'Elijah Just',
      'Callum McCowatt',
      'Kosta Barbarouses',
    ]),
  },
  // ── CONCACAF ──────────────────────────────────────────────────
  {
    code: 'USA',
    name: 'USA',
    fullName: 'Estados Unidos',
    primaryColor: '#002868',
    secondaryColor: '#BF0A30',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 42,
    stickers: makeStickers('USA', 1, [
      'Escudo USSF [FOIL]',
      'Matt Freese',
      'Chris Richards',
      'Tim Ream',
      'Mark McKenzie',
      'Alex Freeman',
      'Antonee Robinson',
      'Tyler Adams',
      'Tanner Tessmann',
      'Weston McKennie',
      'Christian Roldan',
      'Timothy Weah',
      'Foto de Equipo',
      'Diego Luna',
      'Malik Tillman',
      'Christian Pulisic',
      'Brenden Aaronson',
      'Ricardo Pepi',
      'Haji Wright',
      'Folarin Balogun',
    ]),
  },
  {
    code: 'MEX',
    name: 'MEX',
    fullName: 'México',
    primaryColor: '#006847',
    secondaryColor: '#CE1126',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 43,
    stickers: makeStickers('MEX', 1, [
      'Escudo FMF [FOIL]',
      'Luis Malagón',
      'Johan Vásquez',
      'Jorge Sánchez',
      'César Montes',
      'Jesús Gallardo',
      'Israel Reyes',
      'Diego Lainez',
      'Carlos Rodríguez',
      'Edson Álvarez',
      'Orbelín Pineda',
      'Marcel Ruiz',
      'Foto de Equipo',
      'Érick Sánchez',
      'Hirving Lozano',
      'Santiago Giménez',
      'Raúl Jiménez',
      'Alexis Vega',
      'Roberto Alvarado',
      'César Huerta',
    ]),
  },
  {
    code: 'CAN',
    name: 'CAN',
    fullName: 'Canadá',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    textOnPrimary: '#FFFFFF',
    order: 44,
    stickers: makeStickers('CAN', 1, [
      'Escudo CSA [FOIL]',
      'Dayne St. Clair',
      'Alphonso Davies',
      'Alistair Johnston',
      'Samuel Adekugbe',
      'Richairo Živković',
      'Derek Cornelius',
      'Moïse Bombito',
      'Kamal Miller',
      'Stephen Eustáquio',
      'Ismaël Koné',
      'Jonathan Osorio',
      'Foto de Equipo',
      'Jacob Shaffelburg',
      'Mathieu Choinière',
      'Niko Sigur',
      'Tajon Buchanan',
      'Liam Millar',
      'Cyle Larin',
      'Jonathan David',
    ]),
  },
  {
    code: 'HAI',
    name: 'HAI',
    fullName: 'Haití',
    primaryColor: '#003087',
    secondaryColor: '#D21034',
    accentColor: '#000000',
    textOnPrimary: '#FFFFFF',
    order: 45,
    stickers: makeStickers('HAI', 1, [
      'Escudo FHF [FOIL]',
      'Johny Placide',
      'Carlens Arcus',
      'Martin Expérience',
      'Jean-Kevin Duverne',
      'Ricardo Adé',
      'Duke Lacroix',
      'Garven Metusala',
      'Hannes Delcroix',
      'Leverton Pierre',
      'Danley Jean Jacques',
      'Jean-Ricner Bellegarde',
      'Foto de Equipo',
      'Christopher Attys',
      'Derrick Etienne Jr.',
      'Josue Casimir',
      'Ruben Providence',
      'Duckens Nazon',
      'Louicius Deedson',
      'Frantzdy Pierrot',
    ]),
  },
  {
    code: 'CUW',
    name: 'CUW',
    fullName: 'Curazao',
    primaryColor: '#003DA5',
    secondaryColor: '#F9E814',
    accentColor: '#CE1126',
    textOnPrimary: '#FFFFFF',
    order: 46,
    stickers: makeStickers('CUW', 1, [
      'Escudo FFK [FOIL]',
      'Eloy Room',
      'Armando Obispo',
      'Sherel Floranus',
      'Jurien Gaari',
      'Joshua Brenet',
      'Roshon Van Eijma',
      'Shurandy Sambo',
      'Livano Comenencia',
      'Godfried Roemeratoe',
      'Juninho Bacuna',
      'Leandro Bacuna',
      'Foto de Equipo',
      'Tahith Chong',
      'Kenji Gorre',
      'Jearl Margaritha',
      'Jurgen Locadia',
      'Jeremy Antonisse',
      'Gervane Kastaneer',
      'Sontje Hansen',
    ]),
  },
  {
    code: 'PAN',
    name: 'PAN',
    fullName: 'Panamá',
    primaryColor: '#005293',
    secondaryColor: '#DB161B',
    accentColor: '#FFFFFF',
    textOnPrimary: '#FFFFFF',
    order: 47,
    stickers: makeStickers('PAN', 1, [
      'Escudo FEPAFUT [FOIL]',
      'Luis Mejía',
      'Harold Cummings',
      'Fidel Escobar',
      'Erick Davis',
      'César Yanis',
      'Andrés Andrade',
      'José Córdoba',
      'Adalberto Carrasquilla',
      'Édgar Bárcenas',
      'Ricardo Ávila',
      'Freddy Góndola',
      'Foto de Equipo',
      'Alberto Quintero',
      'Aníbal Godoy',
      'Valentín Pimentel',
      'Rolando Blackburn',
      'José Fajardo',
      'Gabriel Torres',
      'Ismael Díaz',
    ]),
  },
];

export const ALL_STICKERS: { team: Team; sticker: Sticker }[] = TEAMS.flatMap((team) =>
  team.stickers.map((sticker) => ({ team, sticker }))
);

export const TOTAL_STICKERS = ALL_STICKERS.length;

export function getStickerById(id: string): { team: Team; sticker: Sticker } | undefined {
  return ALL_STICKERS.find((s) => s.sticker.id === id);
}

export function searchStickers(query: string): { team: Team; sticker: Sticker }[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  return ALL_STICKERS.filter(
    ({ team, sticker }) =>
      sticker.id.toLowerCase().includes(q) ||
      sticker.name.toLowerCase().includes(q) ||
      team.fullName.toLowerCase().includes(q) ||
      team.code.toLowerCase().includes(q)
  ).slice(0, 20);
}
